"""add reviews and approvals tables

Revision ID: 2e80f9811d76
Revises: 6aa03527a1bf
Create Date: 2026-07-05 18:19:45.431613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e80f9811d76'
down_revision: Union[str, Sequence[str], None] = '6aa03527a1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_project_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_project_id'], ['video_projects.id'], name=op.f('fk_approvals_video_project_id_video_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_project_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_type', sa.String(length=16), nullable=False),
    sa.Column('review_version', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('blocking_findings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_project_id'], ['video_projects.id'], name=op.f('fk_reviews_video_project_id_video_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('video_project_id', 'reviewer_type', 'review_version', name='uq_reviews_video_project_reviewer_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('approvals')
    # ### end Alembic commands ###
