"""add llm cache table

Revision ID: 4361fae5cb0a
Revises: b3b1465cd66f
Create Date: 2026-07-04 18:56:35.626653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4361fae5cb0a'
down_revision: Union[str, Sequence[str], None] = 'b3b1465cd66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_caches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('response_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_caches')),
    sa.UniqueConstraint('operation', 'prompt_version', 'input_hash', name='uq_llm_caches_operation_version_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_caches')
    # ### end Alembic commands ###
