"""add video_projects and assets tables

Revision ID: 6aa03527a1bf
Revises: 4361fae5cb0a
Create Date: 2026-07-05 17:48:46.145064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa03527a1bf'
down_revision: Union[str, Sequence[str], None] = '4361fae5cb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('script_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=8), nullable=False),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('output_path', sa.String(length=1024), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_video_projects_script_id_scripts')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_video_projects_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_projects')),
    sa.UniqueConstraint('topic_id', 'generation', name='uq_video_projects_topic_generation')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_project_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_project_id'], ['video_projects.id'], name=op.f('fk_assets_video_project_id_video_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    op.drop_table('video_projects')
    # ### end Alembic commands ###
